language : objective-c
osx_image : xcode7.3
xcode_project: RocketCast.xcodeproj
xcode_scheme: RocketCastTests
xcode_sdk: iphonesimulator9.3
scripts : [ -xcodebuild -workspace RocketCast.xcodeproj -scheme RocketCast -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty ]
