language: objective-c
osx_image : xcode7.3
xcode_project: RocketCast.xcodeproj
xcode_scheme: RocketCast
xcode_sdk: iphonesimulator9.3
script:
  - xcodebuild -project RocketCast.xcodeproj -scheme RocketCast -sdk iphonesimulator 
  - xcodebuild test -project RocketCast.xcodeproj -scheme RocketCastTests -sdk iphonesimulator
